---
fixtures:
  repositories:
    activemq: 'https://github.com/puppetlabs/puppetlabs-activemq.git'
    datacat: 'https://github.com/richardc/puppet-datacat.git'
    java_ks: 'https://github.com/puppetlabs/puppetlabs-java_ks.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    erlang: 'https://github.com/garethr/garethr-erlang.git'
    rabbitmq: 'https://github.com/puppetlabs/puppetlabs-rabbitmq'
    staging: 'https://github.com/nanliu/puppet-staging'
  symlinks:
    mcollective: '#{source_dir}'
